### ISSUE TITLE
Handling of categorical columns

### ISSUE THREAD

**Issue by senovr** [8080labs/ppscore#11]
As it is written in your code, if the column has less then 15 unique values, it is considered as a categorical during fitting.

But, I am facing the following warning during the execution:

Reproducible sample:

```
#importing the libs
import ppscore as pps
import numpy as np
import pandas as pd

#Creating a toy df
#feature column 1
#feature column 2
col1= np.random.randn(10)*10
col2=np.random.randn(10)*10
#feature colum 3- 5 unique values
col3=np.random.choice(range(4),10)

#creating dataframe
df=pd.DataFrame(
{'feature1': col1,
'feature2': col2,
'feature3':col3}
)

#trying to calculate pps matrix
pps.matrix(df)
```

Warning that I observed:

```
anaconda3\envs\DL_py37\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Unknown label type: 'continuous'
```

It is not a new issue, and example of solution (find on [Kaggle)](https://www.kaggle.com/pratsiuk/valueerror-unknown-label-type-continuous) - temporarily convert the data type of feature3 column to categorical with LabelEncoder

**Comment by 8080labs** [comment]
Thank you for your report.
It seems to me that this warning appears in your example because you only generate 10 rows. Therefore, per default all columns are inferred as categorical because they all only have 10 unique values.

However, the values of the columns are float and sklearn does not like to receive float values when using a classifier:
https://stackoverflow.com/questions/41925157/logisticregression-unknown-label-type-continuous-using-sklearn-in-python

TODO: We might want to handle this case in the code via explicitly converting float series with the LabelEncoder

Thank you,
Florian

**Comment by FlorianWetschoreck** [comment]
The main issue here was that the task was inferred wrongly based on the dtype. In the next release, the dtype will determine the task and the issue won't happen any more
