### ISSUE TITLE
Code Improvisation

### ISSUE THREAD

**Issue by RohanTrix** [8080labs/ppscore#40]
I have improvised the Error Handling Code in ppscore. As the same error handling statements were being used repetitively, I have created a class called Check_Error using which it will be quite easy to call the necessary 'raise error' statements. I have tested it too and only 1 test failed but it also failed in the main repo.

As Hacktoberfest has started, I would like to contribute this code as a contribution to open source, so it would be great if you could label this issue and the pull request 'hacktoberfest'.

A pull request has been created on the master branch.

**Comment by FlorianWetschoreck** [comment]
Hi Rohan, thank you for contributing to ppscore.

Unfortunately, I cannot merge the pull request at this time because I have the following 2 opinions:
1) the problem of code duplication for the data type checks is not that pressing (right now)
2) the solution provides more harm to the code base than doing good

To be honest, I also once thought about refactoring this but I did not find a good enough solution that was as readable and easy and did not add unnecessary complexity, thus I just did not bother.

I have some thoughts about how to maybe find a good/better refactoring but honestly I don't think that this problem is worth our time.
In order to respect your time, I want to encourage you to first open an issue with the descriptions of the fix or extension that you want to provide before you sit down and code it. I will then give you some feedback if we should tackle the issue at all and what I think about the implementation idea. Afterwards, you can be sure that your coding time is well spent.

Best,
Florian

**Comment by FlorianWetschoreck** [comment]
Related to #41

**Comment by RohanTrix** [comment]
No issues, thank you for reviewing it!

**Comment by FlorianWetschoreck** [comment]
Maybe #42 or #43 are interesting for you to work on?

**Comment by RohanTrix** [comment]
> Maybe #42 or #43 are interesting for you to work on?
Sure, I'll look into it and let you know.
